#tryExcept.py

l = [1,2]


try:
	print(l[1])
except:
	print("Error: Indice no es Valido")